services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: askida
      POSTGRES_PASSWORD: askida123
      POSTGRES_DB: askida
    ports:
      - "5432:5432"
    volumes:
      - askida_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  askida_pg:
