// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0RXN_l1XzsqjAB3ExWMb1RjBWZjofX1M',
    appId: '1:575069058162:web:77c22bc88509a14350feeb',
    messagingSenderId: '575069058162',
    projectId: 'askida-8da8b',
    authDomain: 'askida-8da8b.firebaseapp.com',
    storageBucket: 'askida-8da8b.firebasestorage.app',
    measurementId: 'G-259J03ZY75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwb4Iuu5x_Rx6tSIXZXCktjoo1jMfZKiw',
    appId: '1:575069058162:android:caaaf2b8e0dd8b2f50feeb',
    messagingSenderId: '575069058162',
    projectId: 'askida-8da8b',
    storageBucket: 'askida-8da8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIwDptsteIABcX7ZYqwcF6xW1UcKjTT4',
    appId: '1:575069058162:ios:547e1cff9144dcd150feeb',
    messagingSenderId: '575069058162',
    projectId: 'askida-8da8b',
    storageBucket: 'askida-8da8b.firebasestorage.app',
    iosBundleId: 'com.example.askida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIwDptsteIABcX7ZYqwcF6xW1UcKjTT4',
    appId: '1:575069058162:ios:547e1cff9144dcd150feeb',
    messagingSenderId: '575069058162',
    projectId: 'askida-8da8b',
    storageBucket: 'askida-8da8b.firebasestorage.app',
    iosBundleId: 'com.example.askida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0RXN_l1XzsqjAB3ExWMb1RjBWZjofX1M',
    appId: '1:575069058162:web:68b576e915235b0450feeb',
    messagingSenderId: '575069058162',
    projectId: 'askida-8da8b',
    authDomain: 'askida-8da8b.firebaseapp.com',
    storageBucket: 'askida-8da8b.firebasestorage.app',
    measurementId: 'G-F93QB4MM7D',
  );
}
